---
name: build & test

on:
  push:
    branches: [main,citmp]
  pull_request:
    branches: [main]

jobs:

  build_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Install deps
        run: sudo apt-get install -y libudev-dev ninja-build
      # TODO: figure out if there's a way to install from apt for the actions
      # ubuntu image. The following fails;
      # 'add-apt-repository universe && apt-get install qt6-charts-dev'
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.2.*'
          modules: 'qtcharts'
      - name: Diagnostics
        run: |
          rustc --version
          cargo --version
          qtpaths --qt-version
      - name: Configure
        run: cmake -G Ninja -S . -B build
      - name: Build
        run: cd build && ninja

  build_debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Install deps
        run: sudo apt-get install -y libudev-dev ninja-build
      # TODO: figure out if there's a way to install from apt for the actions
      # ubuntu image. The following fails;
      # 'add-apt-repository universe && apt-get install qt6-charts-dev'
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.2.*'
          modules: 'qtcharts'
      - name: Diagnostics
        run: |
          rustc --version
          cargo --version
          qtpaths --qt-version
      - name: Configure
        run: cmake -DCMAKE_BUILD_TYPE=Debug -G Ninja -S . -B build
      - name: Build
        run: cd build && ninja

  clang_analyser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Install deps
        run: sudo apt-get install -y libudev-dev ninja-build clang-tools
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.2.*'
          modules: 'qtcharts'
      - name: Diagnostics
        run: |
          rustc --version
          cargo --version
          qtpaths --qt-version
      - name: Configure
        run: scan-build cmake . -B build/analysis
      - name: Build
        run: cd build/analysis && scan-build make

  mac_build_release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Install deps
        run: brew install qt ninja
      - name: Diagnostics
        run: |
          rustc --version
          cargo --version
          qtpaths --qt-version
      - name: Configure
        run: cmake -DCMAKE_BUILD_TYPE=Release -G Ninja -S . -B build
      - name: Build
        run: cd build && ninja

  mac_build_debug:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Install deps
        run: brew install qt ninja
      - name: Diagnostics
        run: |
          rustc --version
          cargo --version
          qtpaths --qt-version
      - name: Configure
        run: cmake -DCMAKE_BUILD_TYPE=Debug -G Ninja -S . -B build
      - name: Build
        run: cd build && ninja
